discover_thailand/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from home import views as home_views
from about import views as about_views
from contact import views as contact_views
from accounts import views as accounts_views
from blog import views as blog_views
from .settings import MEDIA_ROOT
from django.views.static import serve
from threads import views as forum_views
from paypal.standard.ipn import urls as paypal_urls
from paypal_store import views as paypal_views
from products import views as products_views


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', home_views.get_home, name='home'),

    # about url
    url(r'^about/$', about_views.about, name='about'),

    # contact url
    url(r'^contact/$', contact_views.contact, name='contact'),

    # authentication url
    url(r'^register/$', accounts_views.register, name='register'),
    url(r'^profile/$', accounts_views.profile, name='profile'),
    url(r'^login/$', accounts_views.login, name='login'),
    url(r'^logout/$', accounts_views.logout, name='logout'),
    url('^', include('django.contrib.auth.urls')),

    # blog url
    url(r'^media/(?P<path>.*)$', serve, {'document_root': MEDIA_ROOT}),
    url(r'^blog/$', blog_views.post_list),
    url(r'^blog/(?P<id>\d+)/$', blog_views.post_detail),
    url(r'^blog/top', blog_views.top_posts),
    url(r'^post/new/$', blog_views.new_post, name='new_post'),
    url(r'^blog/(?P<id>\d+)/edit$', blog_views.edit_post),

    # forum
    url(r'^forum/$', forum_views.forum),
    url(r'^threads/(?P<subject_id>\d+)/$', forum_views.threads, name='threads'),
    url(r'^new_thread/(?P<subject_id>\d+)/$',  forum_views.new_thread, name='new_thread'),
    url(r'^thread/(?P<thread_id>\d+)/$', forum_views.thread, name='thread'),
    url(r'^post/new/(?P<thread_id>\d+)/$', forum_views.new_post, name='new_post'),
    url(r'^post/edit/(?P<thread_id>\d+)/(?P<post_id>\d+)/$',forum_views.edit_post, name='edit_post'),
    url(r'^post/delete/(?P<thread_id>\d+)/(?P<post_id>\d+)/$', forum_views.delete_post, name='delete_post'),
    url(r'^thread/vote/(?P<thread_id>\d+)/(?P<subject_id>\d+)/$', forum_views.thread_vote, name='cast_vote'),

    # paypal
    url(r'^a-very-hard-to-guess-url/', include(paypal_urls)),
    url(r'^paypal-return', paypal_views.paypal_return),
    url(r'^paypal-cancel', paypal_views.paypal_cancel),

    # products url
    url(r'^products/$', products_views.all_products, name='products'),

]

polls/models.py
from django.db import models
from django.conf import settings
from threads.models import Thread


class Poll(models.Model):
    question = models.TextField()
    thread = models.OneToOneField(Thread, null=True, on_delete=models.DO_NOTHING)

    def __unicode__(self):
        return self.question


class PollSubject(models.Model):
    name = models.CharField(max_length=255)
    poll = models.ForeignKey(Poll, related_name='subjects', on_delete=models.DO_NOTHING)

    def __unicode__(self):
        return self.name


class Vote(models.Model):
    poll = models.ForeignKey(Poll, related_name="votes", on_delete=models.DO_NOTHING)
    subject = models.ForeignKey(PollSubject, related_name="votes", on_delete=models.DO_NOTHING)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='votes', on_delete=models.DO_NOTHING)

threads/models.py
from django.db import models
from django.utils import timezone
from tinymce.models import HTMLField
from django.conf import settings


class Subject(models.Model):

    name = models.CharField(max_length=255)
    description = HTMLField()

    def __unicode__(self):
        return self.name


class Thread(models.Model):

    name = models.CharField(max_length=255)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='threads', on_delete=models.DO_NOTHING,)
    subject = models.ForeignKey(Subject, related_name='threads', on_delete=models.DO_NOTHING,)
    created_at = models.DateTimeField(default=timezone.now)
    tag = models.CharField(max_length=40, blank=True, null=True)

    def __unicode__(self):
        return self.name


class Post(models.Model):

    thread = models.ForeignKey(Thread, related_name='posts', on_delete=models.DO_NOTHING,)
    comment = HTMLField(blank=True)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='posts', on_delete=models.DO_NOTHING,)
    created_at = models.DateTimeField(default=timezone.now)

    def __unicode__(self):
        return self.comment

polls/forms.py
from django import forms
from .models import Poll, PollSubject


class PollForm(forms.ModelForm):
    question = forms.CharField(label="What is your poll about?")

    class Meta:
        model = Poll
        fields = ['question']


class PollSubjectForm(forms.ModelForm):
    name = forms.CharField(label="Poll subject name", required=True)

    def __init__(self, *args, **kwargs):
        super(PollSubjectForm, self).__init__(*args, **kwargs)

        self.empty_permitted = False

    class Meta:
        model = PollSubject
        fields = ['name']

threads/forms.py
from django import forms
from .models import Thread, Post


class ThreadForm(forms.ModelForm):
    name = forms.CharField(label="Thread name")
    is_a_poll = forms.BooleanField(label="Include a poll?", required=False)

    class Meta:
        model = Thread
        fields = ['name']


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['comment']

polls/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render

# Create your views here.

threads/views.py
# coding: utf-8

from django.shortcuts import render, get_object_or_404, redirect
from .models import Subject, Thread, Post
from django.contrib import messages, auth
from django.contrib.auth.decorators import login_required
from django.urls import reverse
from django.template.context_processors import csrf
from .forms import ThreadForm, PostForm
from django.forms import formset_factory
from polls.forms import PollSubjectForm, PollForm
from polls.models import PollSubject


def forum(request):
    return render(request, 'forum/forum.html', {'subjects': Subject.objects.all()})


def threads(request, subject_id):
    subject = get_object_or_404(Subject, pk=subject_id)
    return render(request, 'forum/threads.html', {'subject': subject})


@login_required
def new_thread(request, subject_id):
    subject = get_object_or_404(Subject, pk=subject_id)
    poll_subject_formset_class = formset_factory(PollSubjectForm, extra=3)
    if request.method == "POST":
        thread_form = ThreadForm(request.POST)
        post_form = PostForm(request.POST)
        poll_form = PollForm(request.POST)
        poll_subject_formset = poll_subject_formset_class(request.POST)
        if (thread_form.is_valid() and
                post_form.is_valid() and
                poll_form.is_valid() and
                poll_subject_formset.is_valid()):
            thread = thread_form.save(False)
            thread.subject = subject
            thread.user = request.user
            thread.save()

            post = post_form.save(False)
            post.user = request.user
            post.thread = thread
            post.save()

            poll = poll_form.save(False)
            poll.thread = thread
            poll.save()

            for subject_form in poll_subject_formset:
                subject = subject_form.save(False)
                subject.poll = poll
                subject.save()

            messages.success(request, "You have created a new thread!")

            return redirect(reverse('thread', args=[thread.pk]))

    else:
        thread_form = ThreadForm()
        post_form = PostForm()
        poll_form = PollForm()
        poll_subject_formset = poll_subject_formset_class()

    args = {
        'thread_form': thread_form,
        'post_form': post_form,
        'subject': subject,
        'poll_form': poll_form,
        'poll_subject_formset': poll_subject_formset,
    }

    args.update(csrf(request))

    return render(request, 'forum/thread_form.html', args)


def thread(request, thread_id):
    thread_ = get_object_or_404(Thread, pk=thread_id)
    args = {'thread': thread_}
    args.update(csrf(request))
    return render(request, 'forum/thread.html', args)


@login_required
def new_post(request, thread_id):
    thread = get_object_or_404(Thread, pk=thread_id)

    if request.method == "POST":
        form = PostForm(request.POST)
        if form.is_valid():
            post = form.save(False)
            post.thread = thread
            post.user = request.user
            post.save()

            messages.success(request, "Your post has been added to the thread!")

            return redirect(reverse('thread', args={thread.pk}))
    else:
        form = PostForm()

    args = {
        'form': form,
        'form_action': reverse('new_post', args={thread.id}),
        'button_text': 'Update Post'
    }
    args.update(csrf(request))

    return render(request, 'forum/post_form.html', args)


@login_required
def edit_post(request, thread_id, post_id):
   thread = get_object_or_404(Thread, pk=thread_id)
   post = get_object_or_404(Post, pk=post_id)

   if request.method == "POST":
       form = PostForm(request.POST, instance=post)
       if form.is_valid():
           form.save()
           messages.success(request, "You have updated your thread!")

           return redirect(reverse('thread', args={thread.pk}))
   else:
       form = PostForm(instance=post)


   args = {
       'form' : form,
       'form_action': reverse('edit_post',  kwargs={"thread_id" : thread.id, "post_id": post.id}),
       'button_text': 'Update Post'
   }
   args.update(csrf(request))

   return render(request, 'forum/post_form.html', args)


@login_required
def delete_post(request, thread_id, post_id):
    post = get_object_or_404(Post, pk=post_id)
    thread_id = post.thread.id
    post.delete()

    messages.success(request, "Your post was deleted!")

    return redirect(reverse('thread', args={thread_id}))


@login_required
def thread_vote(request, thread_id, subject_id):
    thread = Thread.objects.get(id=thread_id)

    subject = thread.poll.votes.filter(user=request.user)

    if subject:
        messages.error(request, "You already voted on this! You’re not trying to cheat are you?")
        return redirect(reverse('thread', args={thread_id}))

    subject = PollSubject.objects.get(id=subject_id)

    subject.votes.create(poll=subject.poll, user=request.user)

    messages.success(request, "We've registered your vote!")

    return redirect(reverse('thread', args={thread_id}))

templates/forum/comment_details.html
{% load thread_extras %}
<div class="container">
<div class="details">
   <div class="col-md-6">
       <div class="pull-right bold">
           <time datetime="{{ post.created_at }}">
              Posted: {{ post.created_at|started_time }}
           </time>
       </div>
   </div>
   <div class="col-md-6">
       <div class="pull-left">
           {% if post.user == user %}
                <a href="{% url 'edit_post' thread.id post.id %}"><i class="fa fa-pencil-square-o"></i></a>
                <a href="{% url 'delete_post' thread.id post.id %}"><i class="fa fa-trash-o"></i></a>
            {% endif %}

       </div>
   </div>
   <div class="clearfix"></div>
</div>
</div>

templates/forum/forum.html
{% extends "base.html" %}
{% load thread_extras %}
{% block content %}
   {% load bootstrap_tags %}
   {% for subject in subjects %}

       <div class="container">
           <div class="col-sm-1"></div>
           <section class="forum-subject col-sm-10">
                <table class="table">
                    <thead class="thead-inverse">
                        <tr>
                            <th><h3><a href="{% url "threads" subject.id %}">{{ subject.name }}</a></h3></th>
                            <th>THREADS</th>
                            <th>POSTS</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td class="subject-description">
                                <p>
                                    <a href="{% url "threads" subject.id %}">
                                    {% autoescape off %}{{ subject.description }}{% endautoescape %}
                                    </a>
                                </p>
                            </td>
                            <td>{{ subject.threads.count }}</td>
                            <td>{{ subject|get_total_subject_posts }}</td>
                        </tr>
                    </tbody>
                </table>
            </section>
        <div class="col-sm-1"></div>
       </div>

   {% endfor %}
{% endblock %}

templates/forum/poll.html
{% load thread_extras %}

           {% if thread.poll %}
               <div class="container">
                   <div class="col-md-6">
                       <strong>{{ thread.poll.question }}</strong><br><br>
                            {% for subject in thread.poll.subjects.all %}
                                <div class="col-md-10">
                                    <strong>{{ subject.name }}</strong>
                                    <span class="pull-right">{{ subject|vote_percentage }}%</span>
                                </div>

                           {% autoescape off %}
                                {% user_vote_button thread subject user %}
                           {% endautoescape %}

                        <div class="col-md-10">
                            <div class="progress">
                                <div class="progress-bar progress-bar-info" role="progressbar"
                                    aria-value="{{ subject|vote_percentage }}" aria-valuemin="0"
                                    aria-valuemax="100" style="width:{{ subject|vote_percentage }}%;">
                                </div>
                            </div>
                        </div>
                        {% endfor %}
                   </div>
               </div>
           {% endif %}

templates/forum/post.html
{% load staticfiles %}
{% load emoticons_tags %}

<div class="container">
    <section class="row comment col-md-9">
        <div class="col-md-3 comment-profile">
            <p>{{ post.user.username }}</p>
            <p>{{ post.user.posts.count }} POSTS</p>
        </div>
    <div class="col-md-9 ">
        <div class="comment-content">
            {% autoescape off %}
                {{ post.comment|emoticons }}
            {% endautoescape %}
        </div>
        {% include "forum/comment_details.html" %}
     </div>

    </section>
</div>

templates/forum/post_form.html
{% extends 'base.html' %}
{% load bootstrap_tags %}
{% load staticfiles %}
{% block head_js %}
    <script src="{% static 'vendors/js/tinymce/tinymce.min.js' %}"></script>
    <script>
        tinyMCE.init({
            mode: "textareas",
            theme: "modern",
            plugins: "paste"
        });
    </script>

{% endblock %}
{% block content %}
<div class="container">
    <section class="row ">
        <form method="post" action="{{ form_action }}">
            {% csrf_token %}
            <div class="col-sm-2"></div>
            <div class="col-sm-8">
                {{ form | as_bootstrap }}
                <div class=" row buttons-form">
                    <div class="col-sm-6 form-group">
                        <button type="submit" class="btn btn-primary">Send</button>
                    </div>
                </div>
            </div>
            <div class="col-sm-2"></div>
        </form>
    </section>

</div>
<div class="clearfix"></div>
{% endblock %}

templates/forum/thread.html
{% extends "base.html" %}
{% load thread_extras %}
{% load staticfiles %}
{% block content %}

    <div class="container">
        <div class="row col-sm-12">
            <div class ="post-intro col-sm-5">
                <h2>{{ thread.name }}</h2>
                <hr>
                    <div class="row">
                        <div class="col-sm-5"><b>CREATED</b></div>
                        <div class="col-sm-7"><time datetime="{{ thread.created_at }}">{{ thread.created_at | started_time }}</time></div>
                        <div class="col-sm-5"><b>OWNER</b></div>
                        <div class="col-sm-7">{{ thread.user.username }}</div>
                        <div class="col-sm-5"><b>LAST POST</b></div>
                        <div class="col-sm-7">{% last_posted_user_name thread %}</div>
                        {% if user.is_authenticated %}
                        <div class="col-sm-5"><b></b></div>
                        <div class="col-sm-7"><a href="{% url 'new_post' thread.id %}" class="btn btn-primary">New post</a></div>
                         {% endif %}
                        <hr>
                    </div>
            </div>
            <div class="col-sm-6">
                {% if thread.poll %}
                    {% csrf_token %}
                    {% include 'forum/poll.html' %}
                {% endif %}
            </div>
        </div>
        <div class="col-sm-12 post">
                {% for post in thread.posts.all %}
                    {% include "forum/post.html" %}
                {% endfor %}
        </div>
    </div>

{% endblock %}

templates/forum/thread_form.html
{% extends "base.html" %}
{% load bootstrap_tags %}
{% load staticfiles %}

{% block head_js %}
   <script type="text/javascript" src="{% static 'vendors/js/tinymce/tinymce.min.js' %}"></script>
   <script type="application/javascript">
       tinyMCE.init({mode: "textareas", theme: 'modern', plugins: 'paste'})

   </script>
{% endblock %}


{% block content %}
    <div class="container">
        <section>
            <div class="col-md-9">
                <form method="post" action="{% url 'new_thread' subject.id %}">
                    {% csrf_token %}
                    <div class="form-group">
                        {{ thread_form | as_bootstrap }}
                         <hr>
                        {{ post_form | as_bootstrap }}
                    </div>
                    <div id="poll_form" class="form-group">
                        {{ poll_form|as_bootstrap }}
                        {{ poll_subject_formset.management_form }}
                        {% for poll_subject_form in poll_subject_formset %}
                            {{ poll_subject_form|as_bootstrap }}
                        {% endfor %}
                    </div>
                    <div class="form-group">
                        <button type="submit" class="btn-primary">Post New Thread</button>
                    </div>
                </form>
            </div>
        </section>
    </div>
  <!-- JQuery -->
    <script src="https://code.jquery.com/jquery-2.2.1.min.js"></script>
    <script>
    function showOrHidePollForm() {
        if ($('#id_is_a_poll').is(':checked')) {
            $('#poll_form').show();
        } else {
            $('#poll_form').hide();
        }
    }

    $(document).ready(showOrHidePollForm);
    $('#id_is_a_poll').change(showOrHidePollForm);
</script>
{% endblock %}

templates/forum/thread_item.html
<section class="thread">
 <header>
   <table>
     <tr>
       <td>
         <a href="{% url 'thread' thread.id %}"><h4>{{ thread.name }}</h4></a>
           <p><strong>TAGS</strong>&nbsp;<span>{{ thread.tag}}</span></p>
       </td>
     </tr>
   </table>

 </header>
</section>

templates/forum/threads.html
{% extends "base.html" %}
{% load thread_extras %}
{% load staticfiles %}
{% block content %}

    <div class="container">
        <div class="col-md-12">
            <div class="row">
                <div class="jumbotron"><h3>{{ subject.name }}</h3></div>
            </div>
        </div>

        <div class="col-md-12">
            <div class="col-sm-6">
                <img src="{% static 'images/travel-concept.jpg' %}" class="img-responsive" alt="thailand map">
            </div>

            <div class="col-sm-5 subject-list">
                    {% for thread in subject.threads.all %}
                                <div class="col-md-12 subject-list-items" >
                                    <p>
                                        {% include "forum/thread_item.html" %}
                                    </p>
                                </div>
                    {% endfor %}

                    {% if user.is_authenticated %}
                        <br>
                        <br>
                        <p>
                            <a href="{% url 'new_thread' subject.id %}" class="btn btn-primary">New Thread</a>
                        </p>
                        <hr>
                    {% endif %}
            </div>
        </div>

    </div>
{% endblock %}